version: '3'
services:
  web:
    command: ["./wait-for-it.sh", "db:3306", "--", "./docker/entrypoint.sh"]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    hostname: db
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    ports:
      - "3306:3306"
